### ISSUE TITLE
[Java::JavaIo::FileNotFoundException]: https://XX.XX.XX.XX:443/apis/metrics.k8s.io/v1beta1/pods

### ISSUE THREAD

**Issue by alexo1088** [CloudHealth/helm#82]
Hello,

I'm attempting to install the cloudhealth helm chart into an EKS cluster running 1.23
I've provided the correct keys and cluster name, as well as ensured that all security groups associated with the cluster and the cluster nodes are open to all traffic for the time being while we test, and I continue to get the same error that is preventing metrics from being collected.  

I've attempted to install the helm chart on a number of freshly built clusters, so I know there is nothing installed on the cluster that would prevent a connection.  I've attached the node logs below.

Thank you in advance.
[logs.txt](https://github.com/CloudHealth/helm/files/10058401/logs.txt)

**Comment by kscherme** [comment]
Hi @alexo1088 , it looks like your collector is successfully fetching data from the Kubernetes API and successfully sending this data to our endpoint.  The error you are seeing is only happening when the agent tries to fetch data from Kubernetes metrics server.  This happens when the cluster either does not have `metrics-server` installed or there is a configuration preventing the cluster from reaching metrics server.
